// Validates and bounds everything the extension sends to POST /api/analyze-profile. Rejects
// malformed bodies outright (400); oversized but well-formed text fields are trimmed rather than
// rejected, since a legitimately long About section shouldn't fail the whole request.
import { z } from "zod";

export const MAX_EVIDENCE_ITEMS = 200;
export const MAX_CRITERIA = 50;
export const MAX_TEXT_LENGTH = 2000;
export const MAX_GOAL_DESCRIPTION_LENGTH = 2000;

const criterionImportanceSchema = z.enum(["MUST_HAVE", "PREFERRED", "OPTIONAL", "EXCLUDED"]);

/** Mirrors the extension's (widened) CriterionCategory exactly — see src/models/goal.ts. Kept
 * as its own literal list here (Zod can't derive a runtime schema from a TS type), same
 * reasoning as evidenceSectionSchema below. Missing a value here means the backend REJECTS any
 * analyze-profile request for a goal that uses it (a real bug hit live: criteria generated by
 * POST /api/generate-criteria can carry categories like "membership"/"language" that this schema
 * didn't originally include, silently 400-ing every analysis for that goal and falling back to
 * local — every category criteriaSchema.ts's criterionTypeSchema can produce, plus "context"
 * (the local parser's own generic-domain-vocabulary bucket), must stay listed here). */
const criterionCategorySchema = z
  .enum([
    "role",
    "location",
    "experience",
    "context",
    "other",
    "organization",
    "membership",
    "skill",
    "education",
    "language",
    "leadership",
    "mentoring",
    "competition",
    "service",
    "project",
    "industry",
    "interest",
  ])
  .optional();
export type CriterionCategoryValue = Exclude<z.infer<typeof criterionCategorySchema>, undefined>;
const evidenceStrengthSchema = z.enum(["strong", "moderate", "weak", "missing", "unknown"]);

/** Mirrors models/profile.ts's ProfileSectionName plus the two identity-card pseudo-sections
 * (headline/location) — kept as its own literal list here (rather than importing the TS type,
 * which Zod can't derive a runtime schema from) so a request can never smuggle through a
 * section name that doesn't correspond to anything the evidence-ID scheme actually uses. */
export const evidenceSectionSchema = z.enum([
  "about",
  "experience",
  "education",
  "skills",
  "projects",
  "certifications",
  "organizations",
  "volunteering",
  "languages",
  "headline",
  "location",
]);

export type EvidenceSection = z.infer<typeof evidenceSectionSchema>;

const criterionSchema = z.object({
  id: z.string().min(1).max(200),
  label: z.string().min(1).max(300),
  importance: criterionImportanceSchema,
  category: criterionCategorySchema,
});

const goalSchema = z.object({
  id: z.string().min(1).max(200),
  description: z.string().max(MAX_GOAL_DESCRIPTION_LENGTH * 5).default(""),
  criteria: z.array(criterionSchema).min(1, "At least one criterion is required").max(MAX_CRITERIA),
});

const evidenceItemSchema = z.object({
  id: z.string().min(1).max(100),
  section: evidenceSectionSchema,
  // A generous ceiling only meant to catch garbled/abusive payloads — real trimming down to
  // MAX_TEXT_LENGTH happens in `trimOversizedText`, not here, so a normal long About section
  // never fails validation outright.
  text: z.string().max(MAX_TEXT_LENGTH * 5),
  evidenceType: z.string().min(1).max(50),
});

const profileSchema = z.object({
  identity: z.string().min(1).max(300),
  headline: z.string().max(500).optional(),
  location: z.string().max(300).optional(),
  evidence: z.array(evidenceItemSchema).max(MAX_EVIDENCE_ITEMS),
});

const localCriterionResultSchema = z.object({
  criterionId: z.string().min(1).max(200),
  strength: evidenceStrengthSchema,
  evidenceIds: z.array(z.string().max(100)).max(20).default([]),
});

const localAnalysisSchema = z.object({
  score: z.number().min(0).max(100).nullable(),
  confidence: z.number().min(0).max(1),
  profileExtracted: z.boolean(),
  criterionResults: z.array(localCriterionResultSchema).max(MAX_CRITERIA),
});

export const analyzeProfileRequestSchema = z.object({
  goal: goalSchema,
  profile: profileSchema,
  localAnalysis: localAnalysisSchema,
});

export type AnalyzeProfileRequest = z.infer<typeof analyzeProfileRequestSchema>;

/** Trims oversized text fields down to a safe length rather than rejecting the whole request —
 * called AFTER schema validation succeeds, so a request is never rejected just because one
 * field ran long; it's shortened before it ever reaches the OpenAI prompt. */
export function trimOversizedText(request: AnalyzeProfileRequest): AnalyzeProfileRequest {
  return {
    ...request,
    goal: { ...request.goal, description: request.goal.description.slice(0, MAX_GOAL_DESCRIPTION_LENGTH) },
    profile: {
      ...request.profile,
      evidence: request.profile.evidence.map((item) => ({ ...item, text: item.text.slice(0, MAX_TEXT_LENGTH) })),
    },
  };
}
